defaults:
  - data: default
  - debug: no_debug
  - decode: default
  - logger: default
  - logging: default
  - model: default
  - trainer: test
hydra:
  output_subdir: null
  run:
    dir: .
project_name: usr2
num_workers: 4
log_wandb: False
compile_model: True
gpus:
video:
modality: av
detector: mediapipe 
use_csv_eval: False 
csv_path: 
max_rows:
mouth_roi_root: data/mouth_roi_with_audio 
audio_root: data/audio 
use_mouth_roi_input: True 